-- 코드를 입력하세요
SELECT 
    car.CAR_ID,
    car.CAR_TYPE,
    ROUND(car.DAILY_FEE * 30 * (100 - pl.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR car
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY his
    ON car.CAR_ID = his.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN pl
    ON car.CAR_TYPE = pl.CAR_TYPE
WHERE car.CAR_ID NOT IN
    (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01'
    ) AND pl.DURATION_TYPE like '30%'
GROUP BY car.CAR_ID
HAVING car.CAR_TYPE IN ('세단', 'SUV')
    AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY 3 DESC, 2, 1 DESC