SELECT E.ID,
CASE
    WHEN E.PER <= 0.25 THEN 'CRITICAL'
    WHEN E.PER <= 0.5 THEN 'HIGH'
    WHEN E.PER <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME
FROM(
    SELECT ID,
    PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
    FROM ECOLI_DATA
) AS E
ORDER BY E.ID