-- 코드를 입력하세요
SELECT pd.PRODUCT_ID, pd.PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT pd
JOIN FOOD_ORDER od
    ON pd.PRODUCT_ID = od.PRODUCT_ID
WHERE od.PRODUCE_DATE like "2022-05%"
GROUP BY 1
ORDER BY 3 DESC, 1