-- 코드를 입력하세요
SELECT 
    mb.MEMBER_NAME, 
    rw.REVIEW_TEXT, 
    DATE_FORMAT(rw.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE mb
JOIN REST_REVIEW rw
    ON mb.MEMBER_ID = rw.MEMBER_ID
WHERE mb.MEMBER_ID = 
    (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC LIMIT 1
    )
ORDER BY rw.REVIEW_DATE, rw.REVIEW_TEXT