-- 코드를 작성해주세요
WITH MAX_TABLE AS (
    SELECT 
        MAX(SIZE_OF_COLONY) AS SIZE, 
        YEAR(DIFFERENTIATION_DATE) AS YEAR 
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX_TABLE.SIZE - ed.SIZE_OF_COLONY AS YEAR_DEV,
    ed.ID
FROM ECOLI_DATA ed
JOIN MAX_TABLE ON YEAR(ed.DIFFERENTIATION_DATE) = MAX_TABLE.YEAR
ORDER BY YEAR, YEAR_DEV


